configVersion: 23
# Do not change configVersion above!
# Texter config file

# set language (eng or jpn)
language: jpn

# set timezone
# cf) http://php.net/manual/ja/timezones.php
timezone: false

# When set to true, update notification is displayed at startup
checkUpdate: true

# If you want to disable the command, prease set it to false
canUseCommands: true

# To limit the number of characters, set it to that, if unnecessary, set it to -1
char: 50

# To limit the number of line feeds, set it to that, if unnecessary, set it to -1
feed: 3

# Please specify the world name when setting the world where text can not be set up
world:
  # ex)
  # - world
  # - world-2
